spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=tLtRPEeYNWgJjgpiKJVkrlZUOQQOBLbc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#razorpay
razorpay.key=rzp_test_RsyNM9smue7Zfb
razorpay.secret=EqK8C92fnPJdrwUfB4BIEHJ0